### PR TITLE
Updated the member.yml  || Please add me to this studyGroup

### PR DESCRIPTION
**Pull request by raj-maurya**
# Please add me to this studyGroup.

### CODE REVIEW

**Comment by raj-maurya** [comment]
Dear Aurelia (@auremoser) :

I am glad to hear from you.
Thanks for the introduction and very important guidance.

**Comment by auremoser** [comment]
Great, thanks @raj-maurya !

**Comment by raj-maurya** [comment]
Dear Aurelia (@auremoser) :

Can you please vouch my Mozillian profile: https://mozillians.org/en-US/u/rajkmaurya111/

Thanks!
Raj

**Comment by auremoser** [comment]
Hi @raj-maurya , 
I did! I hope you'll join us for our Community Call Tomorrow if you can, or please update the etherpad with any events in India, at the bottom of the pad, would love to have some updates from the Global South: https://public.etherpad-mozilla.org/p/sciencelab-calls-aug11-2016.

Aurelia

**Comment by raj-maurya** [comment]
Thank you very much @auremoser  for vouching me.

I will definitely join the Community Call Tomorrow.

Thanks again!
Raj

**Pull request closed without merging**
