### PR TITLE
Hello

### PR DESCRIPTION
**Pull request by estum002**
I am trying to make VERY IMPORTANT CHANGES to this

### CODE REVIEW

**Review by jepa — APPROVED** [review]
Yeiiii

**Comment by auremoser** [comment]
Hello @estum002, did you mean to add these changes to the base study group repo?

Perhaps this was meant for your fork of the repo. We have over 400 forks of this project and merging these changes would require a lot of updates for many users for which not all of these changes are relevant. Is it o.k. for me to close this PR? ...assuming it was meant for your study group alone? Thank you!

**Comment by jepa** [comment]
Hi @auremoser you can indeed close it happen exactly as you said! 

cheers

**Comment by auremoser** [comment]
Thank you @jepa!

**Pull request closed without merging**
