### PR TITLE
Travis yml

### PR DESCRIPTION
**Pull request by StuntsPT**
Adds a missing .travis.yml with a node.js environment.

### CODE REVIEW

**Comment by auremoser** [comment]
Hey @StuntsPT , did you mean to commit this back to our base study group repo? or did you intend to keep it to the bionode? 

Is there a way you might cherry pick in the commits that are relevant to the Study Group master? I think there's a few bionode specific things in this commit stack.

Thank you!

**Comment by StuntsPT** [comment]
Apologies @auremoser ! It was a long mozsprint and I was tired.
This was meant to stay in bionode.
I'll solve it right away.

**Comment by auremoser** [comment]
No worries @StuntsPT ! Thank you :) Glad to see activity on the bionode group though 👍

**Comment by StuntsPT** [comment]
@auremoser NP! The mozsprint on Bionode was a lot of fun, and quite fruitful. I feel like we got a lot of stuff done.
Cheers!

**Pull request closed without merging**
