### PR TITLE
Tahzeeb

### PR DESCRIPTION
**Pull request by Tahzeeb**
V nice

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
Sorry this is a misunderstanding , rather than merging with the main `mozillascience:gh-pages` repo from `smilefreak:gh-pages`, we were aiming to get our new members to merge our Otago Study Group repo `smilefreak:gh-pages` from their own fork.

**Comment by katieannemills** [comment]
no problem - let me know if I can help!

**Comment by TomKellyGenetics** [comment]
It's ok I'll pull the changes from the users account and add them to my version of the Otago Study Group. Think I've got it covered, my fault really, didn't make that section of the lesson very clear. We're all still learning right?

**Comment by katieannemills** [comment]
Always :)

**Pull request closed without merging**
