### PR TITLE
I'm done

### PR DESCRIPTION
**Pull request by SaraMati**

### CODE REVIEW

**Comment by auremoser** [comment]
Hey @mbonsma + team!
Are there changes here that you think belong in the master study groups repo, or did this somehow mirror from your fork by mistake?

Aurelia

**Comment by mbonsma** [comment]
@auremoser - I think this was supposed to be just to our fork, so I think this can be closed, but I'll check with @SaraMahallati. It looks like you successfully added yourself to the website, so is it alright if we close this?

**Comment by auremoser** [comment]
Hey @mbonsma , Is it o.k. if I close this issue? Thanks!

**Comment by mbonsma** [comment]
@auremoser, go for it!

**Comment by auremoser** [comment]
Thank you!

**Pull request closed without merging**
