### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### mozillascience/studyGroup now has a Chat Room on Gitter

@acabunoc has just created a chat room. You can visit it here: [https://gitter.im/mozillascience/studyGroup](https://gitter.im/mozillascience/studyGroup?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/mozillascience/studyGroup?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by abbycabs** [comment]
@BillMills I added a hook that will leave a message in this gitter chat if someone forks the repo. Not sure if you want this in the README.

**Comment by katieannemills** [comment]
yeah, maybe better to funnel live conversation at IRC? We're also going to get emails (per your other email), yes?

Thanks for this, webhooks are awesome!

**Comment by auremoser** [comment]
hey @acabunoc, what's the status on this? I'm sorry I let it sit for so long, but if you think it's important I can resolve conflicts and try to merge.

**Comment by abbycabs** [comment]
Hey @auremoser - no worries. It's the just the badge that links to the gitter chat room. Not sure if you're actively using this room, though? https://gitter.im/mozillascience/studyGroup

Bill wanted notifications when someone forked the repo. I set up the notifications in this gitter channel (and created the channel) & email notiifcations.

**Comment by auremoser** [comment]
Great, thank you! Would you like it merged into the readme here or did you both mutually decide to leave it out?

**Comment by abbycabs** [comment]
I think Bill decided to leave it out. It's up to you whether or not you want to use that room! There's a few ppl lurking there, but no real chatter (yet?) :)

**Pull request closed without merging**
